import { useMemo, useState } from "react";
color: COLORS.white,
display: "flex",
alignItems: "center",
justifyContent: "center",
fontWeight: 800,
letterSpacing: 1,
},
h1: { fontSize: 24, margin: "0 0 6px", color: COLORS.text },
lead: { color: "#6b7280", margin: 0 },
label: { display: "block", fontWeight: 600, marginTop: 16, marginBottom: 6 },
input: {
width: "100%",
padding: "12px 14px",
borderRadius: 10,
border: "1px solid #d1d5db",
outline: "none",
fontSize: 16,
},
help: { color: "#6b7280", marginTop: 6 },
resultBox: {
marginTop: 16,
padding: 16,
borderRadius: 12,
background: "#f3f7f6",
border: `1px solid ${COLORS.primary}22`,
},
error: { color: "#b91c1c", fontWeight: 600 },
subtle: { color: "#6b7280", marginBottom: 0 },
days: { fontSize: 36, fontWeight: 800, margin: "4px 0 12px", color: COLORS.text },
plan: { fontSize: 14, color: COLORS.text },
planBadgePrimary: {
background: COLORS.primary,
color: COLORS.white,
padding: "6px 10px",
borderRadius: 999,
},
planBadgeSecondary: {
background: COLORS.secondary,
color: COLORS.white,
padding: "6px 10px",
borderRadius: 999,
},
desc: { color: "#374151", marginTop: 12 },
ctaRow: { display: "flex", gap: 12, marginTop: 12 },
button: {
display: "inline-block",
textDecoration: "none",
padding: "12px 16px",
borderRadius: 12,
fontWeight: 700,
},
buttonPrimary: { background: COLORS.primary, color: COLORS.white },
buttonSecondary: { background: COLORS.secondary, color: COLORS.white },
smallPrint: { color: "#6b7280", marginTop: 12, fontSize: 12 },
footer: { marginTop: 18, textAlign: "center", color: "#6b7280" },
};
